name: Node.js CI

on:
    push:
        branches: [main]

jobs:
    setup:
        runs-on: self-hosted
        environment: cyannav

        steps:
            - name: Checkout main repo
              uses: actions/checkout@v4
            - name: Setup node environment
              uses: actions/setup-node@v4
              with:
                  node-version: "21.x"
                  cache: "npm"
                  cache-dependency-path: |
                      client/package-lock.json
                      server/package-lock.json
            - name: Install node dependencies
              run: |
                  cd client
                  npm i --force
                  cd ../server
                  npm i --force
            - name: Create environment for backend
              run: |
                  cd server
                  rm .env.production
                  touch .env.production
                  echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env.production
                  echo CORS_ORIGIN=${{ vars.CORS_ORIGIN }} >>.env.production
                  echo SERVER_PORT=${{ vars.SERVER_PORT }} >> .env.production
                  echo JWT_EXPIRATION_TIME=${{ vars.JWT_EXPIRATION_TIME }} >> .env.production
                  echo DATABASE_ADDR=${{ vars.DATABASE_ADDR }} >> .env.production


    backend-test:
        needs: setup
        runs-on: self-hosted

        steps:
            - name: Setup node environment
              uses: actions/setup-node@v4
              with:
                  node-version: "21.x"
            - name: Backend API test
              run: |
                  cd server
                  npm test

    deploy:
        if: always()
        needs: setup
        runs-on: self-hosted

        steps:
            - name: Build docker container
              run: |
                  docker compose down -v
                  docker compose up --build -d
